extends Node

const BLUE_GUY_BULLET := 1
const BLUE_GUY_COLLISION := 2
const RAMMER_COLLISION := 3
const SPINNER_BULLET := 4
const SPINNER_COLLISION := 5
const MINION_COLLISION := 6
const WANDERER_COLLISION := 7
const MINIBOSS_BOMB := 8
const MINIBOSS_COLLISION := 9
const MINIBOSS_ORB_EXPLOSION := 10
const BOSS_BULLET := 11
const BOSS_SIDESHIP_COLLISION := 12
const BOSS_MINION_COLLISION := 13
const MINIBOSS_ORB_COLLISION := 14

var HUD:Hud
